### ISSUE TITLE
Add function-level documentation

### ISSUE THREAD

**Issue by mcolom** [CyrilVoisard/ipol_dataset_1#1]
Most of the functions are missing its documentation.
For example, load_metadata has a complete one, but load_XSens, import_XSens, filtre_sig, ... don't.
Please add the documentation to all of them.

**Comment by CyrilVoisard** [comment]
It should be good! Tell me if you see something wrong!

**Comment by mcolom** [comment]
Yes, it's perfect now, thanks!
