### ISSUE TITLE
Write the code fully in English

### ISSUE THREAD

**Issue by mcolom** [CyrilVoisard/ipol_dataset_1#2]
Some functions are given French names, such as "filtre_passe_bas", and there are also comments in French ("# Fin du signal, en enlevant la toute fin qui posait", and others).

This is great for French readers, but in order to have access to an international audience it's important to translate it to English. In any case, it's a requirement in IPOL.

Thanks!

**Comment by CyrilVoisard** [comment]
It should be great, tell me if you see something wrong! Thanks!
