### ISSUE TITLE
Add a FOSS license

### ISSUE THREAD

**Issue by mcolom** [CyrilVoisard/ipol_dataset_1#3]
You need to add a free software license to the program, which is missing now.
I could do it myself, but of course the specific license you decide is your choice.
I'd suggest to use Affero GPL https://www.gnu.org/licenses/agpl-3.0.txt but you can pick any other free license.

To add it, simple add the file to the project and rename it as LICENSE.
Thanks!

**Comment by CyrilVoisard** [comment]
Is it ok ? :)

**Comment by mcolom** [comment]
Absolutely!
